version: '2.1'

services:
  latios:
    container_name: latios
    build:
      context: ./latios
      dockerfile: Dockerfile-dev
    env_file:
      ./docker/.env.dist
  redis:
    environment: 
      REDIS_PASSWORD: core
  database:
    environment:
      MONGODB_DATABASE: latios
      MONGODB_PASSWORD: core
      MONGODB_USERNAME: core