version: '3.3'

services:
  latios:
    container_name: latios
    build:
      context: ./latios
    volumes:
      - ./latios:/usr/src
      - /usr/src/node_modules
    depends_on:
      - redis
      - database
    ports:
      - '8080:8080'
  redis:
    container_name: latios_redis
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    restart: always
  database:
    container_name: latios_database
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - '27017:27017'