version: '3.3'

services:
  latios:
    container_name: latios
    build:
      context: ./latios
      dockerfile: Dockerfile-dev
    env_file:
      - ./docker/.env.dist
  redis:
    logging:
      driver: none
    environment: 
      REDIS_PASSWORD: core
  database:
    logging:
      driver: none
    environment:
      MONGODB_DATABASE: latios
      MONGODB_PASSWORD: core
      MONGODB_USERNAME: core